# Generated by Django 5.0.1 on 2024-01-30 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_productinventory_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productinventory',
            unique_together={('product',)},
        ),
    ]
